<!--
Every web page has the following structure:

    Head
        headSectionContent (mostly metadata)
    Body
        siteHeader
            siteBanner (horizontal navigation bar)
            callToAction (may change with each page it is on)

        mainContent
            primaryContent  (~60% width)
            secondaryContent (~30% width)

        footer content (legals, disclaimer, etc.)
-->
<!doctype html>
<html>
<head>
    <?php
    // the dbConnection include is a special case - it creates no output
    // but sets up
    include_once("dbConnect.php");
    //
    //
    // Some of our output-creating includes require certain variables to be set prior to calling
    // (This is a stylistic requirement, not a technical one - defaults are used if )
    // headSectionContent.php will set a default value of "Untitled Page"
    $pageTitle="Townsville Community Music Centre: Home";
    include("headSectionContent.php");
    ?>
</head>

<body>

<div id="colourHeader">
</div id="colourHeader">

<div id="siteCenter">
  <p>Email:
    <input name="logOnEmail" type="text" size="30" maxlength="20">
  </p>
  <p>Password:	
    <input name="logOnPassword" type="password" size="30" maxlength="20">
  </p>
<input name="button" type="button" value="Log On">
<input name="button" type="button" value="Log Off">
      <?php
	  //Wrong password message
      if (isset($_SESSION['msg'])) {
	echo "<p style='color:red'>".$_SESSION['msg']."</p>"; 
	//remove the message since it has been displayed.
	unset($_SESSION['msg']);
	}
	?>
    
   	<?php
	//logout button
    if (isset($_SESSION['msgG'])) {
		echo"<form>";
		echo "<p style='color:green'>".$_SESSION['msgG']."</p>"; 
		echo '<input type="button" name="logout" id="logout" value="Logout" onClick="location.href=\'../Scripts/Logout.php\'"/>'; 
		echo"</form>";
	}
	
?> 
    <?php
    // includes which fill div elements should have the div open and close tags
    // set in the calling file.
    echo "<div class='header'>";
        // Must specify which section we represent before including siteNavigationBanner.php
        $sectionName="home";
        include_once("siteNavigationBanner.php");
    echo "</div class='header'>";
    ?>

    <div id="contentLeft">
        <!-- May be generated by an included php file -->
    </div id="contentLeft">
 
    <div id="contentRight">
    </div id="contentRight">

</div id="siteCenter">

<div id="footer">
<?php
// Page footer is a good place to close the db connection
// No need to access the database after footer content is printed
include("siteFooter.php");
$dbh = null;
?>
</div id="footer">
<h2>Membership</h2>
<p align="right">
<div>
  <p>Townsville      Civic Theatre <br>
    41      Boundary Street,<br>
    Townsville<br>
    P.O.      Box 1006<br>
    Townsville      4810</p>
</div>
<div>
  <p><strong>Phone     </strong>(07) 4724 2086<br>
    <strong>Mobile  </strong>  0402      255 182 <br>
    <strong>Email </strong>admin@townsvillemusic.org.au <br>
    <strong>Website  </strong>www.townsvillemusic.org.au  </p>
  <p>ABN:  35 039      662 787    Not GST Registered</p>
</div>
<div></div>
<div>
  <p>Individual Membership subscription is $25 per year.</p>
  <p>The Music Centre is also registered as a Deductible Gift      Recipient. Any extra donations are tax-deductible! </p>
</div>
<div>
  <p>Please make cheques      payable to Townsville Community Music Centre Inc, and post to: <br>
    PO Box 1006, Townsville, Qld 4810</p>
  <p>Or  Deposit to account:<br>
    Account      Name:   Townsville Community Music      Centre Inc.<br>
    Account      Number:        141 475 053<br>
    Bank                    Bendigo Bank<br>
    BSB      Number:      633 000</p>
  <p>It      is also possible to pay online by Visa, Mastercard or PayPal<br>
    From our website - www.townsvillemusic.org.au</p>
</div>
<h2>Membership Application Form</h2>
<p>Date:
  <input name="date" type="text" size="30" maxlength="20">
</p>
<p>First Name:
  <input name="firstName" type="text" size="30" maxlength="20">
</p>
<p>Surname:
  <input name="surname" type="text" size="30" maxlength="20">
</p>
<p>Postal Address:
  <textarea name="address" cols="35" rows="4"></textarea>
</p>
<p>Phone Day:
  <input name="phoneDay" type="text" size="30" maxlength="20">
</p>
<p>After Hours:
  <input name="afterHours" type="text" size="30" maxlength="20">
</p>
<p>Mobile:
  <input name="mobile" type="text" size="30" maxlength="20">
</p>
<p>Email:
  <input name="email" type="text" size="30" maxlength="20">
</p>
<p>(It is preferable to email all communication, newsletters etc.)</p>
<p>Comment:</p>
<textarea name="comment" cols="70" rows="15"></textarea>
<p>We value your comments and suggestions</p>

</body>
</html>
